import Head from "next/head";
import { IAnime } from "types/anime";
import { useEffect, useState } from "react";
import Table from "components/Table";
import Panel from "components/Panel";
import axios from "axios";

const Home = ({}) => {
  const [animes, setAnimes] = useState<IAnime[]>([]);

  useEffect(() => {
    const getAnimes = async () => {
      try {
        const response = await axios.get<{ data: IAnime[] }>("/api/animes");

        setAnimes(response.data.data);
      } catch (error) {}
    };

    getAnimes();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen p-4">
        <Panel />
        <div className="overflow-auto">
          <Table data={animes} />
        </div>
      </main>
    </div>
  );
};

export default Home;
