import Head from "next/head";
import { IAnime, Statuses } from "types/anime";
import {
  createColumnHelper,
  useReactTable,
  getCoreRowModel,
  flexRender,
} from "@tanstack/react-table";
import { useMemo } from "react";
import statusCollection from "constants/statusCollection";

const animes: IAnime[] = [
  {
    id: 16498,
    name: "Shingeki no Kyojin",
    russian: "Атака титанов",
    status: Statuses.Dropped,
  },
  {
    id: 1,
    name: "Shingeki no Kyojin",
    russian: "Атака титанов",
    status: Statuses.InProgress,
  },
];

const columnHelper = createColumnHelper<IAnime>();

const Home = () => {
  const columns = useMemo(
    () => [
      columnHelper.accessor((row) => `${row.name} / ${row.russian}`, {
        id: "name",
        cell: (anime) => <i>{anime.getValue()}</i>,
        header: () => <span>Name</span>,
      }),
      columnHelper.accessor((row) => statusCollection[row.status], {
        id: "status",
        cell: (anime) => <i>{anime.getValue()}</i>,
        header: () => <span>Status</span>,
      }),
    ],
    []
  );

  const table = useReactTable({
    data: animes,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex justify-center items-center">
        <table className="max-w-4xl w-full text-sm text-left text-gray-500">
          <thead className="text-xs text-gray-700 uppercase bg-gray-50">
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <th key={header.id} className="py-3 px-6">
                    {flexRender(
                      header.column.columnDef.header,
                      header.getContext()
                    )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {table.getRowModel().rows.map((row) => (
              <tr key={row.id} className="bg-white border-b">
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id} className="py-4 px-6">
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
